apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        sidecar.jaegertracing.io/inject: 'true'
    labels:
        app: paraparty-xiaobin
    name: bawling-minidouyin-user-http
    namespace: bawling-minidouyin-user-http
spec:
    selector:
        matchLabels:
            name: paraparty-xiaobin
    template:
        metadata:
            labels:
                app: bawling-minidouyin-user-http
                branch: dev
                version: ${BUILD_NUMBER}-${CI_COMMIT_ID}
                name: bawling-minidouyin-user-http
                dream-app: bawling-minidouyin-user-http
                dream-unit: bawling-minidouyin-user-http
        spec:
            imagePullSecrets:
                -   name: regcred
            containers:
                -   image: ${IMAGE}
                    imagePullPolicy: IfNotPresent
                    name: bawling-minidouyin-user-http
                    readinessProbe:
                        httpGet:
                            path: /health_check
                            port: 14514
                        initialDelaySeconds: 5
                        periodSeconds: 5
                        successThreshold: 2
                    livenessProbe:
                        failureThreshold: 3
                        httpGet:
                            path: /health_check
                            port: 14514
                        initialDelaySeconds: 10
                        periodSeconds: 10
                        timeoutSeconds: 1
                    # lifecycle:
                    #     preStop:
                    #         exec:
                    #             command:
                    #                 - sleep
                    #                 - "20"
                    envFrom:
                        -   configMapRef:
                                name: env-config
                        -   configMapRef:
                                name: config
            terminationGracePeriodSeconds: 30